Kasaan_MapScripts::
	.byte 0


Slide_Ice_Trees_Axes::
	lock
	msgbox Slide_Ice_Trees_Axes_Text_0
	release
	end


Logs_Tripping::
	lock
	msgbox Logs_Tripping_Text_0
	release
	end


Axes_Trees::
	lock
	msgbox Axes_Trees_Text_0
	release
	end


Sus_Mas_Tree::
	lock
	msgbox Sus_Mas_Tree_Text_0
	release
	end


Holey_Logs::
	lock
	msgbox Holey_Logs_Text_0
	release
	end


Kasaan_Playground_Sign::
	lock
	msgbox Kasaan_Playground_Sign_Text_0
	release
	end


Kasaan_Gym_Sign::
	lock
	msgbox Kasaan_Gym_Sign_Text_0
	release
	end


Slide_Ice_Trees_Axes_Text_0:
	.string "Falling down always feels better when\n"
	.string "you land on the ice with a hatchet in\l"
	.string "your head.\p"
	.string "There seems to be bloodstains on the\n"
	.string "handles of the axes.$"

Logs_Tripping_Text_0:
	.string "Logs for kids to trip over. Credited for\n"
	.string "handing out concussions to more than\l"
	.string "sixty-nine children.$"

Axes_Trees_Text_0:
	.string "A fun and safe place for children to\n"
	.string "play!\p"
	.string "Huh?\n"
	.string "You're asking what that lump under the\l"
	.string "snow is? The one with a bit of red? I\l"
	.string "have absolutely NO idea what you are\l"
	.string "talking about.$"

Sus_Mas_Tree_Text_0:
	.string "This is the sus-mas tree. Every\n"
	.string "Thursday, we:\p"
	.string "- Kiss the tree\n"
	.string "- play Among Us under the tree\l"
	.string "- Praise the tree\l"
	.string "- Hug the tree\l"
	.string "- Don't chop the tree down\l"
	.string "- Don't light the tree on fire\p"
	.string "For more details, please visit\n"
	.string "theannoyingsite.com.$"

Holey_Logs_Text_0:
	.string "These are the Holey logs. That's\n"
	.string "because they have holes. Plus, they're\l"
	.string "holy. Every Tuesday, we:\p"
	.string "- Kiss the logs\n"
	.string "- Hug the logs\l"
	.string "- Add more logs when the children break\l"
	.string "them\l"
	.string "- Praise the logs\l"
	.string "- Thank the logs for everything, even if\l"
	.string "you are a bum\p"
	.string "For more details on activities, visit\n"
	.string "theannoyingsite.com.$"

Kasaan_Playground_Sign_Text_0:
	.string "The famous playground of Traf.$"

Kasaan_Gym_Sign_Text_0:
	.string "Gym$"
